### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by gustavao** [shodgson/mifos-chart-of-accounts#2]
Hello friend how, I consult you because I have a problem and I have not found how to solve it, if you know the solution, I am commenting I am using the script:

./importCoA.sh -u mifos -p password -t default -a https: // localhost: 8443 / fineract-provider / -f sampleCoA.csv

after executing the script it throws me the following error:

[ERROR] Could not create general ledger account with name [pba1]
Response from server:

It does not matter what values I put in, it always gives me the same error.

Regards

**Comment by shodgson** [comment]
If there is no response from the server, then it is possible that the
script is not reaching your fineract server at all.  Double-check your
address (do not include any spaces in
https://localhost:8443/fineract-provider/) and that you have your SSL
certificates installed correctly, etc.
